### ISSUE TITLE
liblz4 compability

### ISSUE THREAD

**Issue by ludvigak** [NVIDIA/nvcomp#20]
A nice feature would be the ability to use nvcomp to decompress data compressed using [liblz4](https://github.com/lz4/lz4), and vice versa, in order to have more flexibility when sending data between computers. It is presently not straightforward to figure out how to translate between the lz4 data format used by nvcomp and liblz4's block format or frame format.

Built-in support in the form of API calls would of course be nice, but it would also be really useful to have a short documentation outlining how the formats can be translated.

**Comment by bkarsin** [comment]
This is a nice feature that would improve usability, but it is not currently planned for the short term.

It is not clear that this can easily be done due to the chunked approach that nvcomp uses for parallelization.  Nvcomp splits the input dataset into many small chunks, compresses them in parallel, and saves metadata for each.  Likewise, nvcomp can decompress efficiently on the GPU because the many small chunks can be decompressed in parallel.  This causes issues both in terms of metadata translation and compression/decompression performance when attempting to mix nvcomp and other LZ4 compressors.

**Comment by ludvigak** [comment]
I see, thank you for the reply!

For what it's worth, the nvcomp chunks could probably be mapped to LZ4 frames:
https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md

**Comment by bkarsin** [comment]
Thanks for pointing this out.  We will look into this and if it matches well, we will consider adding a translation tool or instructions in an upcoming release.

**Comment by nv-dlasalle** [comment]
While we don't support LZ4 frames (due to the inherent serial dependency), we now support LZ4 blocks from the CPU based compressor. See https://github.com/NVIDIA/nvcomp/blob/main/examples/lz4_cpu_compression.cu for an example.
