### ISSUE TITLE
Concurrent compression kernels 

### ISSUE THREAD

**Issue by Manoj-red-hat** [NVIDIA/nvcomp#42]
Hi All,

I have problem like:-

Stream of K threads which are running on CPU, intermediately they require compression/decompression.

I was thinking of leveraging the GPU for this comp/decom problem.

 But the point is I need K kernel to handle K threads, just wondering 
What would be the resource requirement for this nvcomp, if I need to plan say 8 concurrent kernels ? 

Thread 1---------com---dec---com--->
.
.
Thread K ----------com--dec---com-->

**Comment by mnicely** [comment]
What you're asking would be handled by the CUDA framework. Each CPU thread would create a separate CUDA context and each CPU thread would launch nvCOMP kernels on that CUDA context. The GPU will handle context switching at resources become available. I suggest you google CUDA + Multiprocessing.

**Comment by fwyzard** [comment]
My understanding is that using multiple CUDA contexts on the same device is inefficient, because [operations from different contexts cannot run concurrently](https://forums.developer.nvidia.com/t/multiple-cuda-contexts-per-device-in-a-single-process/42429/2).

Rather than using multiple contexts, I would suggest creating [one CUDA stream per thread](https://developer.download.nvidia.com/CUDA/training/StreamsAndConcurrencyWebinar.pdf), one set of work buffers er stream, and using the nvcomp async API, _e.g._ `compressor.compress_async(..., stream)` to run multiple compression/decompression in parallel.

**Comment by mnicely** [comment]
> My understanding is that using multiple CUDA contexts on the same device is inefficient
While it's not optimal because of overhead, every application is different. And if you have activate [MPS](https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf) (Multi-Process Service) contexts can run concurrently on Pascal+ HW.

> Rather than using multiple contexts, I would suggest creating one CUDA stream per thread
Unless you pass around a CUDA context using the Driver API, a new context will be created by each thread. The slides you reference don't discuss concurrent CPU threads targeting a single GPU, only multiple streams.

Let's back up, while the hardware can functionality support up to 32 streams (I think) realistically only 2-4 will actually run in parallel. And this only happens when they are underutilizing hardware resources. 

If no resources are available, kernels in different streams will be serialized.

So the first thing that should be tested is 2 CPU threads & 2 GPU contexts, with MPS, and see what overlap, if any, occurs.

**Comment by fwyzard** [comment]
In my opinion using multiple streams instead of multiple contexts should be easier (CUDA runtime vs driver API), simpler (no need to try and recover some performance with MPS) and faster.

Anyway, these are just suggestions for @Manoj-red-hat .

**Comment by fwyzard** [comment]
> Unless you pass around a CUDA context using the Driver API, a new context will be created by each thread.

Mhm, I don't think so, but of course I can be wrong: can you point to any documentation in this regard ?

**Comment by mnicely** [comment]
> In my opinion using multiple streams instead of multiple contexts should be easier (CUDA runtime vs driver API), simpler (no need to try and recover some performance with MPS) and faster.

This is very true, but if use case consists of multiple CPU threads trying to compress/decompress multiple files simultaneously multiple streams within a single CPU threads won't work.

@Manoj-red-hat I believe there's enough information here to answer your questions. I'm going to close, feel free to reopen if you have more questions.
