### ISSUE TITLE
[QST] Strange behavior with cascade batch compressor

### ISSUE THREAD

**Issue by ser-mk** [NVIDIA/nvcomp#58]
I have found some of datasets can’t be compressed or converted using batch nvcomp compressor without a runtime error.
This is the case for a sequence of integers that doesn't compress well. Let’s see
I got [test_cascaded_batch.cpp](https://github.com/NVIDIA/nvcomp/blob/v2.2.0/tests/test_cascaded_batch.cpp) and make [minimal example ](https://github.com/ser-mk/nvcomp/blob/v2.2.0_test/tests/test_batch_cant_compress.cpp)for demo
If you run the example, you get result (checked on tag v2.1.0 and v2.2.0):
<img width="720" alt="image" src="https://user-images.githubusercontent.com/6123791/157967996-fcd8933d-5461-4177-8ff7-3a419738d98b.png">
You can see the input date in the output
![image](https://user-images.githubusercontent.com/6123791/157970075-eeef2dc5-3468-47fa-b40e-7e7c0b1692f5.png)
Function [nvcompBatchedCascadedCompressAsync](https://github.com/NVIDIA/nvcomp/blob/v2.1.0/src/lowlevel/CascadedBatch.cu#L1596) return the nvcompSuccess code
I did some research It and saw…
Compress algorithm broke on this [step](https://github.com/NVIDIA/nvcomp/blob/v2.1.0/src/lowlevel/CascadedBatch.cu#L649)
```c
 if (output + padded_out_bytes / sizeof(uint32_t) > output_limit) {
    return BlockIOStatus::out_of_bound;
  }
```
Output buffer exceeds the calculated limit from [here](https://github.com/NVIDIA/nvcomp/blob/v2.1.0/src/lowlevel/CascadedBatch.cu#L829)
```c
    // the metadata. It is users responsibility to guarantee this requirement.
    uint32_t* output_limit
        = output_buffer + roundUpDiv(partition_metadata_size, sizeof(uint32_t))
          + roundUpDiv(input_bytes, sizeof(uint32_t));
```
output_limit var have a capacity the partition metadata and input data and seemingly have to save delta data or byte packing data
This is not save because [chunk_metadata_size](https://github.com/NVIDIA/nvcomp/blob/v2.1.0/src/lowlevel/CascadedBatch.cu#L863) take a cut of part of the output buffer
```c
      // Move current output pointer as the end of chunk metadata
      current_output_ptr += chunk_metadata_size / sizeof(uint32_t);
```
Perhaps that's on purpose. May be ... The nvcomp library would prefers  to choice  minimal output data. The uncompressed data + minimal partition metadata is less the bad compressed data + partition metadata + chunk metadata. I need to get modified data for a dataset that doesn't compress well. I am going to use the modified data for further a cascade algorithm of my own devising.

**Comment by ndickson-nvidia** [comment]
Thanks so much for reporting this!  Sorry that it took a little while to reply.  The out of bounds access is due to a mistake in the test_cascaded_batch.cpp file.  It shouldn't be implementing its own `max_compressed_size` function, but should instead be calling the `nvcompBatchedCascadedCompressGetMaxOutputChunkSize` API function.  Using that function, the max compressed size is 248 bytes, so it avoids the out of bounds access.  We'll be sure to fix the test file, and I'll double-check to see if there might be other places doing something like this, though at first glance, this looks like it might be the only place.

As for the lack of compression with the first 4 sets of options, if the compression wouldn't result in a smaller size than the original data, it just falls back to the uncompressed data.  For the case of using deltas (differences) alone, all of the deltas after the first value are 1, but because bit packing isn't enabled, all of the 1's would be stored as a full byte, resulting in no compression.  For the case of RLE (run-length encoding) alone, there are no repeated consecutive values, so RLE (storing values and repeat counts of those values that are all 1) would be larger than the original data.  RLE with bit packing would bit pack all of the repeat counts that are 1, but since the unique value range (size 240) spans all 8 bits of the data type, the values can't be reduced, meaning that the size of the counts and the values are still large than the original data.  With bit packing alone, the value range is still 240 large, so it still requires all 8 bits, meaning the output would be identical to the original data anyway.  With deltas and bit packing, all of the deltas, (ignoring the first value) are 1, so can be bit packed down to 1 bit (or potentially zero bits, but I haven't double-checked whether that's supported), meaning that there's a lot less data than the original. 
 Hopefully that clears things up.

**Comment by Rolariali** [comment]
Thanks for your answer! Your pretty explain this case!
