### ISSUE TITLE
Compression size

### ISSUE THREAD

**Issue by zinir** [NVIDIA/nvcomp#73]
In high level quick start. The compressed buffer size is always larger than the original buffer. Please help. What am i missing

**Comment by Rajon010** [comment]
~Hi zinir,~
~Can you please show how to solve this issue? I'm having the same problem now.~

I have found an explanation. Turns out that this issue is mainly about the data to be compressed. In high_level_quickstart_example.cpp, the test data is uniformly distributed in the range from 0 to maximum limit of uint8 (255), so there is no information redundancy in the data. That is, we do need that much space to express the data, and there is nothing to be compressed. To see the compression effect, one can change 255 to a smaller number (e.g., 63), use more regular data (e.g., [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, ...]), or use zstd (achieving better compression ratio in most cases) instead of lz4.
