### ISSUE TITLE
How can I make built binary packages?

### ISSUE THREAD

**Issue by newjavaer** [NVIDIA/nvcomp#75]
How can I use the source code of version 2.3 to compile the so library?

**Comment by ndickson-nvidia** [comment]
Since 2.3, the libraries are available on the NVIDIA Developer nvCOMP page: https://developer.nvidia.com/nvcomp  Hopefully the [README.md](https://github.com/NVIDIA/nvcomp/blob/main/README.md) and examples give enough info to be able to use the libraries.  If you run into any issues, though, please feel free to ask.
